apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: daemonset-logging
spec:
  template:
    metadata:
      labels:
        app: daemonset-logging
    spec:
      nodeSelector:
        app: daemonset-logging
      containers:
        - name: webserver
          image: nginx
          ports:
          - containerPort: 80
